app:
  name: "prehrajto-autopilot"
  app_name: "Prehraj.to AutoPilot"
  version: "0.1.3"
  buildNumber: "2620_1716"
  description: "Prehraj.to AutoPilot - Desktop application for video management"
  environment: "development"
config:
  MAX_UPLOAD_SIZE: 2147483648  # 2 GB
  MAX_SSL_CHUNK_SIZE: 32768    # 8 KB (SSL record max is 16KB) 8192 / 16284 / 32768 / 65536