app:
  name: "prehrajto-autopilot"
  app_name: "Prehrajto.cz AutoPilot"
  version: "0.1.4"
  buildNumber: "2621_0030"
  description: "Prehrajto.cz AutoPilot - Desktop application for video management"
  environment: "development"
config:
  MAX_UPLOAD_SIZE: 2147483648  # 2 GB
  MAX_SSL_CHUNK_SIZE: 32768    # 8 KB (SSL record max is 16KB) 8192 / 16284 / 32768 / 65536